Repository AbhineshJha/Redstore, pull requests merged in 2023-10, with the labels that each got.

#9 I have added new features and also updated the UI
  Css/product.css
  Css/style.css
  index.html
  product.html
Labels: hacktoberfest

#25 Fixes#15/navbarhover and color
  Css/style.css
  index.html
Labels: good first issue, hacktoberfest

#34 Clicking on LOGO returns to Index, Used relative path, fixed bug with image display, Improved Readme.md, Refactored codebase
  Css/login.css
  README.md
  about.html
  contactform.html
  index.html
  login.html
  product.html
Labels: good first issue, hacktoberfest

#35 updated the css and html
  Css/style.css
  index.html
Labels: good first issue, hacktoberfest

#50 Adding Favicon in all Web Pages !!
  about.html
  contactform.html
  img/favicon.png
  index.html
  login.html
  product.html
Labels: good first issue, hacktoberfest, hacktoberfest2023
